spring:
  cloud:
    gateway:
      routes:
        # 精确的路由放在高优先级，模糊的放在低优先级
        # 配置商品服务的路由
        - id: product_route
          uri: lb://mall_route
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters: # 路径重写 /api/** -> /renren-fast/**
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

