spring:
  cloud:
    gateway:
      routes:
        # 精确的路由放在高优先级，模糊的放在低优先级
        # 配置商品服务的路由
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>/?.*), /product/$\{segment}
         # 配置会员的路由
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/member/(?<segment>/?.*), /member/$\{segment}
        # 三方请求路由
        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters: # 路径重写 /api/** -> /renren-fast/**
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        # 域名的路由，结合nginx， 放在最后
        - id: mall_host_route
          uri: lb://mall-product
          predicates:
            - Host=**.mall.com