spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

   # rabbitmq 配置
  thymeleaf:
    cache: false
#  rabbitmq:
#    addresses: 192.168.91.128
#    port: 5672
#    virtual-host: /

mybatis-plus:
  # mapper扫描
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      # id 自增
      id-type: auto
server:
  port: 10001
logging:
  level:
    com.apple.product: debug